### ISSUE TITLE
feat: specify a process for authenticating a farcaster id with a signed message

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/protocol#26]
Specify the system which third party applications can use to verify ownership of a Farcaster ID with a signed message.

**Comment by galligan** [comment]
This would be awesome @varunsrin. With XMTP we're working on a method where we support EIP-1271 smart contract validation methods to then enable messaging capabilities for them. Something similar for Farcaster would mean that XMTP could then support secure messaging between Farcaster ID's.

**Comment by javalasers** [comment]
Don't know if this counts as the same issue or a different one, but it appears that today you cannot use the "Connect Address" flow to connect your farcaster account to a gnosis safe, for example. You can use WalletConnect to connect the farcaster connection page to your gnosis safe address, but when you try to trigger the signature itself, it does not work. Would love to be able to link the NFTs in my personal gnosis safe to my farcaster profile gallery as well...
