### ISSUE TITLE
feature: data structure to mark user mentions in casts 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/protocol#30]
## What?
User mentions should be tracked in casts with an array data structure that can store upto 5 mentions

## Why?

- Allows mentions to be rendered consistently across all clients
- Allows users to type text that may collide with a mention without explicitly creating a mention (e.g. @xyz on twitter said...) 
- Prevents spammy behavior like tagging a very large number of users

## How?

If a user wants to write a cast that renders as `hello @bob and @alice!` where bob and alice are tagged and have fids 123 and 456, the cast body would be generated as follows: 

```ts
const body =  {
  text: "hello %0% and %1%",
  mentions: [fid:123,fid:456],
  ...
}
```

### Protocol

The proposed design is to keep the mention data outside of the `text` field while retaining a pointer to it. Each `CastShort` message will have a `mentions` array that can contain 0-5 `fids`. These fids can be pointed to from a cast's text with the strings `%0%` ... `%4%`.  

A benefit to this approach is that each tag also adds a deterministic amount to the cast.text length (3 chars) instead of it being dependent on the length of the username. The `%<num>%` strings are also unlikely to collide with text typed by a user which makes parsing this data structure easier for clients. 

The formal type definition for cast short then becomes: 

```ts
type CastShortTextBody = {
  embed: Embed;
  mentions?: [];  // max of 5 items 
  text: string;
  schema: 'farcaster.xyz/schemas/v1/cast-short-text';
  parentUri?: URI;
};
```

### Clients 

When rendering a Cast with a mention, clients can follow this simple pseudocode: 

- For every match of `/\%[0-4]\%/gm` in `cast.text`, if a `mentions[num]` exists, where `num` is the number matched
- Replace `$<num>$` with `@<fname>` if it exists, and `!<fid>` otherwise, and link to the users profile 

Casts can also kick off side effects like sending out notifications when they receive such a cast. Note that a single fid can be mentioned multiple times in the same cast, but no more than 5 unique fids can be mentioned.

A user who wishes to tag the fname bob which owns the fid 123 may type `hello @bob`, which should cause the client to look up the fname bob, find its fid and create this underlying data structure: 

```ts
const body =  {
  text: "hello $0$ ",
  mentions: [fid:123],
  ... 
}
```

A user who wishes to tag the fid 456 which does not have an fname may type `hello !456`, which should cause the client to validate that 456 is an fid and then create this data structure: 

```ts
const body =  {
  text: "hello $0$ ",
  mentions: [fid:456],
  ... 
}
```

A user may also choose to tag the fid 123 which owns the name bob by writing `hello !123`, in which case we recommend that clients change the ui to `hello @bob` while generating the following data structure 

```ts
const body =  {
  text: "hello $0$ ",
  mentions: [fid:123],
  ... 
}
```

### Todo

- [ ] add to protocol spec
- [ ] add to farcaster hub

**Comment by pfletcherhill** [comment]
A few comments/questions:
* What happens if a user writes $1$ without adding to the mentions list?
* What would be a reason we'd want to mention an fname vs an fid? Is the idea that some mentions should reference an fname even if it moves between fids? 
* The `!<fid>` vs `@<fname>` syntax is a bit weird to me. Could we lean on our URI framework instead and use `@` for both followed by a URI (i.e. `@fid:8789213729`)?
* The 5 mentions limit seems somewhat arbitrary. Do we need it? It's much higher, but the number of mentions is technically already bounded by the character limit of the cast.

**Comment by sds** [comment]
To piggyback off of @pfletcherhill's point about using URIs, we could use URIs for username references on other platforms, e.g.
* Twitter: `@tw:someusername`
* GitHub: `@gh:someotherusername`

**Comment by varunsrin** [comment]
good feedback, i'm going to clean up the original issues above, and then respond to any outstanding concerns

**Comment by varunsrin** [comment]
@pfletcherhill  

1. if a user were to write `$1$` and their client did not add a mention it would get rendered as text.
2. at the protocol level the data structure contains an fid. however, when inputting the mention the user should be able to type either the fid or fname and have the client resolve it 
3. i like this suggestion for the protocol level, but to keep the `!` and `@` for UI level tags 
4. We should have some upper bound to prevent people from writing spammy casts. I'm open to this being 6 or 10, but 5 seems like a round-ish and reasonably high number for the average cast.

**Comment by varunsrin** [comment]
also updating the protocol level specification to store the mention as `fid:123` instead of `!123`. While more verbose it gives us more flexibility to expand to other providers like Github (ghb:bob) or Twitter (twt:bob) down the line. 

considering using did's but the verbosity of the identifier is very high, and space is a premium on the hubs.

**Comment by gsgalloway** [comment]
I'm wondering if, for consistency, both `mentions` and `follows` should use the same scheme for addressing users. Right now `follows` use a full `farcaster://fid:123` URL and mentions would just use the `fid:123` part

**Comment by gsgalloway** [comment]
> To piggyback off of @pfletcherhill's point about using URIs, we could use URIs for username references on other platforms, e.g.
> 
> * Twitter: `@tw:someusername`
> * GitHub: `@gh:someotherusername`

This is an interesting point that maybe suggests using something with more structure. I'm not sure if there's an existing standard for addressing github and twitter users in the same context. The protocol could fall back to just using their HTTP(S) profile links to address GH and TW accounts. So like
```
mentions: [
  'farcaster://fid:123',
  'https://github.com/gsgalloway'
]
```
This may be over-engineering, I'm not sure how much demand there would be for @mentioning users outside of the farcaster platform

**Comment by sds** [comment]
@gsgalloway Totally fair. I was perhaps prematurely optimizing to reduce the size of the payload. I don't see any reason we couldn't use arbitrary URLs to reference profiles on other platforms. Regardless of representation, clients will need to decide whether they add support for such references.

**Comment by pfletcherhill** [comment]
Theoretically, I like the idea of being able to reference twitter, github, or other social accounts, but I'm having a hard time imagining how clients would implement that or what users would do with it. Those aren't necessarily reasons not to do it, but it does smell a bit premature.

Bear with me, but I also want to revisit whether we want to have a mentions list at all. The mentions list forces clients that want to let their users mention other users to have a certain level of sophistication (i.e. implementing some sort of typeahead when a user starts typing "@.." on their new cast page). Otherwise, users of that client may try to mention other users (even by fid) and those won't be counted as mentions because they're not replaced with a token in the text and entry in the mentions list. What if we let users write mentions as purely `@fid:123` or `@fname:pfh` in the text of a cast? I know it's going back on a lot of the reasons we like the mentions list, but I wonder whether there's virtue in making casts really dumb and text-based at first. A bit like Roam Research or Markdown or a CLI—there's no special data structure, just text.

(Worth mentioning that I don't have a strong opinion either way, but I thought it was worth bringing up before we encode this in the hubs and messages.)

**Comment by varunsrin** [comment]
i agree that optimizing for other social applications is premature, and we should focus on the problem at hand. 

the main arguments i'd make against this proposal would be: 

1. requiring lengthier prefixes like `@fname:pfh` makes it cumbersome to type. if we are taking a text-only approach, better to fall back to a simple `@` and `!` prefix for names and ids. 

2. it's actually not desirable to let users mention by username, since usernames may change or expire. this will happen far more often than on social networks we're used to, because names cost money. that may leave a lot of inaccurate references around. 

we can skip the  mentions array, but at the point where clients are reading @names and swapping them for !ids because of (2), adding this requirement is minimal overhead and makes parsing a lot easier for other clients.

**Comment by varunsrin** [comment]
after further discussions in the dev chat)

- we don't want to support mentioning anything other than fid at the data representation level in casts.  clients can remap fid to fnames, ens, github and other thing associated with this by profile metadata. that keeps the data representation lightweight and simple. 

- we want to change the token delimiter to `%` from `$`which is less overloaded (and easier to type on EU keyboards) 

otherwise, we're staying with the original proposal as it stands.

**Comment by i001962** [comment]
Where is 'dev chat' and how does one get invited to it? I have several questions and suggestions about the scheme and it's extensibility. Where is the best place to ask those?

**Comment by varunsrin** [comment]
best place to propose new ideas is as discussions in the github repo

**Comment by varunsrin** [comment]
this has been merged into the protocol specification
