### ISSUE TITLE
feat: add metadata to signed messages

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/protocol#9]
First draft out for review [here](https://farcasterxyz.notion.site/Metadata-Set-40e7e10f0e044f34b343aa44a25917cd)

**Comment by varunsrin** [comment]
based on chat with pfh, metadata will pushed to a future version of farcaster (v2.1 most likely)

**Comment by sds** [comment]
We ended up using the UserData message type for this purpose. Closing as completed.
